### ISSUE TITLE
It doesn't tell me if I won or not

### ISSUE THREAD

**Issue by sethanderson** [zachwil/rps#2]
In the rps.py code, it will spit out what I chose and what the computer picked, but it doesn't give a result at the end. 
Looks like it might be related to comparing lowercase strings.

**Comment by zachwil** [comment]
Fix'd.

**Comment by sethanderson** [comment]
https://github.com/sethanderson/rps/commit/8e04b9e80ca9a59cd12fe022e54e7b72759fdc86
